// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_gen.go

package nvlist

type nvpair struct {
	Size       int32
	Name_sz    int16
	Reserve    int16
	Value_elem int32
	Type       nvtype
}
type nvlist struct {
	Version int32
	Nvflag  uint32
	Priv    uint64
	Flag    uint32
	Pad     int32
}

type nvHeader struct {
	Encoding  int8
	Endian    int8
	Reserved1 int8
	Reserved2 int8
}
